server:
  port: 8080


# 多数据源路由配置
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: uId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lottery?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
      db01:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lottery_01?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
      db02:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lottery_02?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lottery?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml

# Dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: N/A #multicast://224.5.6.7:1234
  protocol:
    name: dubbo
    port: 20880
    host: 0.0.0.0
  scan:
    base-packages: cn.itedus.lottery.rpc

## 新增日志配置（添加在文件末尾）
#logging:
#  level:
#    root: info
#    org.apache.dubbo: debug
#    cn.itedus.lottery: debug
